
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace LunchMoneyManager.Console {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MainView : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.ListView debtorListView;
        
        private Terminal.Gui.Views.TableView transactionTableView;
        
        private Terminal.Gui.Views.Label amountLabel;
        
        private Terminal.Gui.Views.Button addDebtorButton;
        
        private Terminal.Gui.Views.Button addDebtButton;
        
        private Terminal.Gui.Views.Button repayDebtButton;
        
        private Terminal.Gui.Views.Button quitButton;
        
        private void InitializeComponent() {
            this.quitButton = new Terminal.Gui.Views.Button();
            this.repayDebtButton = new Terminal.Gui.Views.Button();
            this.addDebtButton = new Terminal.Gui.Views.Button();
            this.addDebtorButton = new Terminal.Gui.Views.Button();
            this.amountLabel = new Terminal.Gui.Views.Label();
            this.transactionTableView = new Terminal.Gui.Views.TableView();
            this.debtorListView = new Terminal.Gui.Views.ListView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Lunch Money Manager";
            this.debtorListView.Width = 17;
            this.debtorListView.Height = 19;
            this.debtorListView.X = 1;
            this.debtorListView.Y = 1;
            this.debtorListView.Visible = true;
            this.debtorListView.CanFocus = true;
            this.debtorListView.ShadowStyle = null;
            this.debtorListView.Data = "debtorListView";
            this.debtorListView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.debtorListView.Source = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.Add(this.debtorListView);
            this.transactionTableView.Width = 58;
            this.transactionTableView.Height = 5;
            this.transactionTableView.X = Pos.Right(debtorListView) + 0;
            this.transactionTableView.Y = 0;
            this.transactionTableView.Visible = true;
            this.transactionTableView.CanFocus = true;
            this.transactionTableView.ShadowStyle = null;
            this.transactionTableView.Data = "transactionTableView";
            this.transactionTableView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.transactionTableView.FullRowSelect = true;
            this.transactionTableView.Style.AlwaysShowHeaders = false;
            this.transactionTableView.Style.ExpandLastColumn = true;
            this.transactionTableView.Style.InvertSelectedCellFirstCharacter = false;
            this.transactionTableView.Style.ShowHorizontalHeaderOverline = true;
            this.transactionTableView.Style.ShowHorizontalHeaderUnderline = true;
            this.transactionTableView.Style.ShowVerticalCellLines = true;
            this.transactionTableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable transactionTableViewTable;
            transactionTableViewTable = new System.Data.DataTable();
            System.Data.DataColumn transactionTableViewTableReferenceColumn;
            transactionTableViewTableReferenceColumn = new System.Data.DataColumn();
            transactionTableViewTableReferenceColumn.ColumnName = "Transaction reference";
            transactionTableViewTable.Columns.Add(transactionTableViewTableReferenceColumn);
            System.Data.DataColumn transactionTableViewTableAmountColumn;
            transactionTableViewTableAmountColumn = new System.Data.DataColumn();
            transactionTableViewTableAmountColumn.ColumnName = "Amount";
            transactionTableViewTable.Columns.Add(transactionTableViewTableAmountColumn);
            this.transactionTableView.Table = new Terminal.Gui.Views.DataTableSource(transactionTableViewTable);
            this.Add(this.transactionTableView);
            this.amountLabel.Width = Dim.Auto();
            this.amountLabel.Height = Dim.Auto();
            this.amountLabel.X = Pos.Right(transactionTableView) - (this.amountLabel.GetAutoWidth() + 6);
            this.amountLabel.Y = 18;
            this.amountLabel.Visible = true;
            this.amountLabel.CanFocus = false;
            this.amountLabel.ShadowStyle = null;
            this.amountLabel.Data = "amountLabel";
            this.amountLabel.Text = "0.00";
            this.amountLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.End;
            this.Add(this.amountLabel);
            this.addDebtorButton.Width = Dim.Auto();
            this.addDebtorButton.Height = Dim.Auto();
            this.addDebtorButton.X = 2;
            this.addDebtorButton.Y = 20;
            this.addDebtorButton.Visible = true;
            this.addDebtorButton.CanFocus = true;
            this.addDebtorButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.addDebtorButton.Data = "addDebtorButton";
            this.addDebtorButton.Text = "Add Debtor";
            this.addDebtorButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.addDebtorButton.IsDefault = false;
            this.Add(this.addDebtorButton);
            this.addDebtButton.Width = Dim.Auto();
            this.addDebtButton.Height = Dim.Auto();
            this.addDebtButton.X = Pos.Right(addDebtorButton) + 0;
            this.addDebtButton.Y = 20;
            this.addDebtButton.Visible = true;
            this.addDebtButton.CanFocus = true;
            this.addDebtButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.addDebtButton.Data = "addDebtButton";
            this.addDebtButton.Text = "Add Debt";
            this.addDebtButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.addDebtButton.IsDefault = false;
            this.Add(this.addDebtButton);
            this.repayDebtButton.Width = Dim.Auto();
            this.repayDebtButton.Height = Dim.Auto();
            this.repayDebtButton.X = Pos.Right(addDebtButton) + 0;
            this.repayDebtButton.Y = 20;
            this.repayDebtButton.Visible = true;
            this.repayDebtButton.CanFocus = true;
            this.repayDebtButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.repayDebtButton.Data = "repayDebtButton";
            this.repayDebtButton.Text = "Repay Debt";
            this.repayDebtButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.repayDebtButton.IsDefault = false;
            this.Add(this.repayDebtButton);
            this.quitButton.Width = Dim.Auto();
            this.quitButton.Height = Dim.Auto();
            this.quitButton.X = Pos.Right(transactionTableView) - (this.quitButton.GetAutoWidth() + 5);
            this.quitButton.Y = 20;
            this.quitButton.Visible = true;
            this.quitButton.CanFocus = true;
            this.quitButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.quitButton.Data = "quitButton";
            this.quitButton.Text = "Quit";
            this.quitButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.quitButton.IsDefault = false;
            this.Add(this.quitButton);
        }
    }
}
